version: '3'
services:
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lnmp-network
    depends_on:
      - mysql
      - php-fpm
  php-fpm:
    build: ./php
    hostname: php-fpm
    volumes:
      - ./nginx/www:/var/www/html
    networks:
      - lnmp-network 
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - lnmp-network
    environment:
      - MYSQL_ROOT_PASSWORD="supersafepassword"
      - MYSQL_ROOT_HOST="172.18.0.*"
networks:
  lnmp-network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
